# Generated by Django 4.0.4 on 2022-05-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_active_remove_user_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
